### ISSUE TITLE
Cannot get this to work

### ISSUE THREAD

**Issue by wisemoth** [GMMan/dengo-plug-and-play-chimes-patch#3]
I have a Densha de Go P&P v1.13, and have tried:

- 2  USB Memory sticks, both with at least 2GB free
- 1 and 2 partitions - only or first partition formatted FAT32
- partition table style GPT and MBR
- 3 different OTG Hubs
- with/without HDMI cabler inserted into DDG

I've never seen the door light come in.  For many of the above permutations the game just continues to launch.  For one of the hubs the screen goes black after the first 3 screens of license text in Japanese; but the script doesn't seem to chain load (since I don't see the DDG door light)

One thing is that I was preparing the USB stick(s) with Windows `diskpart`...

Any other clues?

Thanks for the work though! I'd love to get it working.

**Comment by arnauos** [comment]
Some USB drives are not working at all, are yours USB3.x? Ideally having just one partition, fat32 and in MBR mode has been confirmed to work, but the USB drive has to be detected...

**Comment by wisemoth** [comment]
>  are yours USB3.x

No, I don't believe so. I've now tried off-brand 4GB, Sandisk  Cruzer Blad 8GB, and a TDK 16GB (which ironically has an OTG option, but no way to split the power).

**Comment by GMMan** [comment]
Are you using an angle adapter or an actual OTG hub?

**Comment by wisemoth** [comment]
I've used a few OTG hubs; but no angle adapters.

**Comment by GMMan** [comment]
Is the P&P from the 2018 batch or the 2020 batch?

**Comment by wisemoth** [comment]
I'm not super sure how to find out, but I did buy it new this year from Amazon JP.

I'm hoping that means a tweak to make the script load...

Perhaps the shell script name needs to change, or some button combo at power on to influence the bootloader?

**Comment by GMMan** [comment]
Did you clone the repo or download as an archive? If you cloned, try downloading it as an archive. Might be possible that your files are using Windows line endings, and Linux shells don't like that.

**Comment by wisemoth** [comment]
Interesting. I cloned. I'll try the tarball.

I thought about Linux/Windows but one checked the file modes in git... Then I remembered the USB is formatted as FAT32 anyway.

**Comment by wisemoth** [comment]
Thanks for the help - it now works!

It was indeed Windows line endings after git checkout.  It's not just the shell script that needed repair, as I then run into problems when the `sha1sum` attempts to check `223_1.vag`.  I decided to just take the tarball as you suggested, and that worked perfectly.

Thank you so much for this work. I look forward to any other patches you make for the DTG P&P!
