### ISSUE TITLE
hardware versions supported

### ISSUE THREAD

**Issue by matphillips** [GMMan/dengo-plug-and-play-chimes-patch#6]
Will this work with all hardware versions? They released a 'new' one in 2020, darker gray color. Is the patch compatible? I have no unit yet and want to purchase one that I can enhance to this patch.

**Comment by arnauos** [comment]
Get the new one. With the original release you have the risk of it having the old firmware that is full of bugs.

**Comment by GMMan** [comment]
The game version needs to be the one mentioned in the readme because the patch is specifically designed for that version. If the original version has been sent back to be patched, it should be OK.
